const Map = {
  所: ['station', undefined],
  用户类型: ['userType', undefined],
  用户编号: ['userID', undefined],
  用户名称: ['userName', undefined],
  表计资产号: ['meteredAssetNumber', undefined],
  数据日期: ['dataDate', undefined],
  CT: ['CT', undefined],
  PT: ['PT', undefined],
  A相电压: ['phaseVoltage', 1],
  B相电压: ['phaseVoltage', 1],
  C相电压: ['phaseVoltage', 1],
  A相电流: ['phaseCurrent', 1],
  B相电流: ['phaseCurrent', 1],
  C相电流: ['phaseCurrent', 1],
  零序电流: ['zeroSequenceCurrent', undefined],
  有功功率: ['effectivePower', undefined],
  A相有功功率: ['phaseEffectivePower', 1],
  B相有功功率: ['phaseEffectivePower', 1],
  C相有功功率: ['phaseEffectivePower', 1],
  无功功率: ['reactivePower', undefined],
  A相无功功率: ['phaseReactivePower', 1],
  B相无功功率: ['phaseReactivePower', 1],
  C相无功功率: ['phaseReactivePower', 1],
  线路名称: ['lineName', undefined],
  资产编号: ['assetNumber', undefined],
  出厂编号: ['factoryNumber', undefined],
  综合倍率: ['comprehensiveRatio', undefined],
  变压器容量: ['transformerCapacity', undefined],
  接线方式: ['modeOfConnection', undefined],
  电压: ['voltage', undefined],
  标定电流: ['calibrationCurrent', undefined],
};

export default Map;
