export const Map = {
  所: ['station', undefined],
  用户类型: ['userType', undefined],
  用户编号: ['userID', undefined],
  用户名称: ['userName', undefined],
  表计资产号: ['meteredAssetNumber', undefined],
  数据日期: ['dataDate', undefined],
  CT: ['CT', undefined],
  PT: ['PT', undefined],
  A相电压: ['phaseVoltage', 1],
  B相电压: ['phaseVoltage', 1],
  C相电压: ['phaseVoltage', 1],
  A相电流: ['phaseCurrent', 1],
  B相电流: ['phaseCurrent', 1],
  C相电流: ['phaseCurrent', 1],
  零序电流: ['zeroSequenceCurrent', undefined],
  有功功率: ['effectivePower', undefined],
  A相有功功率: ['phaseEffectivePower', 1],
  B相有功功率: ['phaseEffectivePower', 1],
  C相有功功率: ['phaseEffectivePower', 1],
  无功功率: ['reactivePower', undefined],
  A相无功功率: ['phaseReactivePower', 1],
  B相无功功率: ['phaseReactivePower', 1],
  C相无功功率: ['phaseReactivePower', 1],
  线路名称: ['lineName', undefined],
  资产编号: ['assetNumber', undefined],
  出厂编号: ['factoryNumber', undefined],
  综合倍率: ['comprehensiveRatio', undefined],
  变压器容量: ['transformerCapacity', undefined],
  接线方式: ['modeOfConnection', undefined],
  电压: ['voltage', undefined],
  标定电流: ['calibrationCurrent', undefined],
};

export const ResultMap = {
  station: '所',
  userType: '用户类型',
  userID: '用户编号',
  userName: '用户名称',
  meteredAssetNumber: '表计资产号',
  dataDate: '数据日期',
  CT: 'CT',
  PT: 'PT',
  phaseVoltageA: 'A相电压',
  phaseVoltageB: 'B相电压',
  phaseVoltageC: 'C相电压',
  phaseCurrentA: 'A相电流',
  phaseCurrentB: 'B相电流',
  phaseCurrentC: 'C相电流',
  zeroSequenceCurrent: '零序电流',
  effectivePower: '有功功率',
  phaseEffectivePowerA: 'A相有功功率',
  phaseEffectivePowerB: 'B相有功功率',
  phaseEffectivePowerC: 'C相有功功率',
  reactivePower: '无功功率',
  phaseReactivePowerA: 'A相无功功率',
  phaseReactivePowerB: 'B相无功功率',
  phaseReactivePowerC: 'C相无功功率',
  lineName: '线路名称',
  assetNumber: '资产编号',
  factoryNumber: '出厂编号',
  comprehensiveRatio: '综合倍率',
  transformerCapacity: '变压器容量',
  modeOfConnection: '接线方式',
  voltage: '电压',
  calibrationCurrent: '标定电流',
  isError: '是否异常',
  info: '错误信息',
  lineMod: '接线方式',
  phaseSeq: '向序',
  elementsRealAngleA: '一元件真实角度',
  elementsRealAngleB: '二元件真实角度',
  elementsRealAngleC: '三元件真实角度',
  elementsBasicAngleA: '一元件基础角度',
  elementsBasicAngleB: '二元件基础角度',
  elementsBasicAngleC: '三元件基础角度',
  elementsVoltageLagAngleA: '一元件电压滞后角度',
  elementsVoltageLagAngleB: '二元件电压滞后角度',
  elementsVoltageLagAngleC: '三元件电压滞后角度',
  elementsCurrentLagAngleA: '一元件电流滞后角度',
  elementsCurrentLagAngleB: '二元件电流滞后角度',
  elementsCurrentLagAngleC: '三元件电流滞后角度',
  elementsAccessMethods: '二次线接入方式',
  correctPowerA: '一元件实际功率',
  correctPowerB: '二元件实际功率',
  correctPowerC: '三元件实际功率',
}
